version: '3.8'

services:
    heloworld:
        image: helloworld:latest
        container_name: helloworld-container
        ports:
            - "8383:80"    
        volumes:
            - hwc:/usr/share/nginx/html
            - ./html2:/usr/share/nginx/html
            
    heloworld2:
        image: helloworld:latest
        container-name: helloworld-container2
        ports:
            - "8384:80"
        volumes:
            - hwc:/usr/share/nginx/html
            - ./html2:usr/share/nginx/html